# Generated by Django 5.0 on 2023-12-21 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS361_Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prof',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS361_Project.course'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS361_Project.course_labsection'),
        ),
        migrations.AlterField(
            model_name='ta',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS361_Project.course'),
        ),
        migrations.AlterField(
            model_name='ta',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS361_Project.course_labsection'),
        ),
    ]
