# Generated by Django 5.0 on 2023-12-21 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS361_Project', '0002_course_prof_alter_instructor_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='CS361_Project.instructor'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_courses', to='CS361_Project.course'),
        ),
    ]
